---
- name: Create vmail user and homedir
  user: 
      name: "{{ item.name }}"
      uid: "{{ item.uid }}"
      home: "{{ item.homedir }}"
      append: yes
      createhome: yes
      state: present
  with_items: "{{unix_users}}"

- name: Copy dovecot password file
  copy: src={{ dovecot_passwd_file }} dest="/etc/dovecot/passwd.db" mode="0600" owner=dovecot group=dovecot
  notify: restart dovecot

- name: Copy and populate dovecot templates
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner=root
  notify: restart dovecot
  with_items: 
      - { src: "etc_dovecot_conf.d_99-mail-stack-delivery.conf", dest: "/etc/dovecot/conf.d/99-mail-stack-delivery.conf", mode: '0644' }
      - { src: "etc_dovecot_conf.d_10-auth.conf", dest: "/etc/dovecot/conf.d/10-auth.conf", mode: "0644", owner: "root", group: "dovecot" }
      - { src: "etc_dovecot_conf.d_10-mail.conf", dest: "/etc/dovecot/conf.d/10-mail.conf", mode: "0644", owner: "root", group: "dovecot" }
      - { src: "etc_dovecot_conf.d_15-mailboxes.conf", dest: "/etc/dovecot/conf.d/15-mailboxes.conf", mode: "0644", owner: "root", group: "dovecot" }
      - { src: "etc_dovecot_conf.d_auth-system.conf.ext", dest: "/etc/dovecot/conf.d/auth-system.conf.ext", mode: "0644", owner: "root", group: "dovecot" }

 
- name: Key and Cert symlinks
  file: src={{ item.src }} dest={{ item.dest }} state=link
  notify: restart dovecot
  with_items:
      - { src: "/etc/ssl/certs/ssl-cert-snakeoil.pem", dest: "/etc/dovecot/dovecot.pem" }
      - { src: "/etc/ssl/private/ssl-cert-snakeoil.key", dest: "/etc/dovecot/private/dovecot.pem" }
