---
- name: Copy postfix templates and populate
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner=root
  with_items: 
      - { src: "etc_postfix_main.cf", dest: "/etc/postfix/main.cf", mode: '0644' }
      - { src: "etc_postfix_master.cf", dest: "/etc/postfix/master.cf", mode: '0644' }
      - { src: "etc_mailname", dest: "/etc/mailname", mode: '0644' }
      - { src: "etc_postfix_canonical", dest: "/etc/postfix/canonical", mode: '0644' }
      - { src: "etc_aliases", dest: "/etc/aliases", mode: '0644' }
      - { src: "etc_postfix_virtual", dest: "/etc/postfix/virtual", mode: '0644' }
      - { src: "etc_postfix_virtual-mailbox-domains", dest: "/etc/postfix/virtual-mailbox-domains", mode: '0644' }
      - { src: "etc_postfix_virtual-mailbox-users", dest: "/etc/postfix/virtual-mailbox-users", mode: '0644' }
  notify: postmap files
